# Site settings
title: Thematic Cartography Guide
description: > # this means to ignore newlines until "baseurl:"
  A short, friendly guide to basic principles of thematic mapping.
baseurl: "/thematic-cartography" # the subpath of your site, e.g. /blog/
url: "http://axismaps.github.io" # the base hostname & protocol for your site
twitter_username: axismaps
github_username:  axismaps
githuburl: "http://github.com/axismaps/thematic-cartography"

# Build settings
markdown: kramdown
